# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/sony/extra/extra/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/sony/extra/extra

PRODUCT_COPY_FILES += \
    vendor/sony/extra/extra/proprietary/product/etc/default-permissions/pre_grant_permissions_oem.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/default-permissions/pre_grant_permissions_oem.xml \
    vendor/sony/extra/extra/proprietary/product/etc/permissions/com.google.protobuf-2.3.0.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/com.google.protobuf-2.3.0.xml \
    vendor/sony/extra/extra/proprietary/product/etc/permissions/com.sonyericsson.music.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/com.sonyericsson.music.xml \
    vendor/sony/extra/extra/proprietary/product/etc/permissions/com.sonymobile.extmonitorapp.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/com.sonymobile.extmonitorapp.xml \
    vendor/sony/extra/extra/proprietary/product/etc/permissions/com.sonymobile.home.resourceprovider.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/com.sonymobile.home.resourceprovider.xml \
    vendor/sony/extra/extra/proprietary/product/etc/permissions/com.sonymobile.mmwdiapi.somc-mmwdiapi.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/com.sonymobile.mmwdiapi.somc-mmwdiapi.xml \
    vendor/sony/extra/extra/proprietary/product/etc/permissions/com.sonymobile.moviecreator.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/com.sonymobile.moviecreator.xml \
    vendor/sony/extra/extra/proprietary/product/etc/sysconfig/extmonitorapp-initial-package-stopped-states.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/sysconfig/extmonitorapp-initial-package-stopped-states.xml \
    vendor/sony/extra/extra/proprietary/system_ext/etc/permissions/com.dolby.daxservice.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.dolby.daxservice.xml \
    vendor/sony/extra/extra/proprietary/system_ext/etc/permissions/com.sony.threesixtyra.audiofx.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.sony.threesixtyra.audiofx.xml \
    vendor/sony/extra/extra/proprietary/system_ext/etc/permissions/com.sonyericsson.soundenhancement.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.sonyericsson.soundenhancement.xml \
    vendor/sony/extra/extra/proprietary/system_ext/etc/permissions/com.sonymobile.colorgamut.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.sonymobile.colorgamut.xml \
    vendor/sony/extra/extra/proprietary/system_ext/etc/permissions/com.sonymobile.gesdklibrary.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.sonymobile.gesdklibrary.xml \
    vendor/sony/extra/extra/proprietary/system_ext/etc/permissions/jp.co.sony.threesixtyra.system.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/jp.co.sony.threesixtyra.system.xml \
    vendor/sony/extra/extra/proprietary/vendor/etc/DrangeparaAAC128.bin:$(TARGET_COPY_OUT_VENDOR)/etc/DrangeparaAAC128.bin \
    vendor/sony/extra/extra/proprietary/vendor/etc/DrangeparaAAC256.bin:$(TARGET_COPY_OUT_VENDOR)/etc/DrangeparaAAC256.bin \
    vendor/sony/extra/extra/proprietary/vendor/etc/DrangeparaAAC64.bin:$(TARGET_COPY_OUT_VENDOR)/etc/DrangeparaAAC64.bin \
    vendor/sony/extra/extra/proprietary/vendor/etc/DrangeparaMP3_128.bin:$(TARGET_COPY_OUT_VENDOR)/etc/DrangeparaMP3_128.bin \
    vendor/sony/extra/extra/proprietary/vendor/etc/DrangeparaMP3_160.bin:$(TARGET_COPY_OUT_VENDOR)/etc/DrangeparaMP3_160.bin \
    vendor/sony/extra/extra/proprietary/vendor/etc/DrangeparaMP3_192.bin:$(TARGET_COPY_OUT_VENDOR)/etc/DrangeparaMP3_192.bin \
    vendor/sony/extra/extra/proprietary/vendor/etc/DrangeparaPCM441.bin:$(TARGET_COPY_OUT_VENDOR)/etc/DrangeparaPCM441.bin \
    vendor/sony/extra/extra/proprietary/vendor/etc/DrangeparaPCM48.bin:$(TARGET_COPY_OUT_VENDOR)/etc/DrangeparaPCM48.bin \
    vendor/sony/extra/extra/proprietary/vendor/etc/XTC_speaker_coef.hki:$(TARGET_COPY_OUT_VENDOR)/etc/XTC_speaker_coef.hki \
    vendor/sony/extra/extra/proprietary/vendor/etc/alc.speaker.bin:$(TARGET_COPY_OUT_VENDOR)/etc/alc.speaker.bin \
    vendor/sony/extra/extra/proprietary/vendor/etc/audio/audio-silence.wav:$(TARGET_COPY_OUT_VENDOR)/etc/audio/audio-silence.wav \
    vendor/sony/extra/extra/proprietary/vendor/etc/dsx_param_file.bin:$(TARGET_COPY_OUT_VENDOR)/etc/dsx_param_file.bin \
    vendor/sony/extra/extra/proprietary/vendor/etc/init/android.hardware.media.c2@1.0-threesixty-ra-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.media.c2@1.0-threesixty-ra-service.rc \
    vendor/sony/extra/extra/proprietary/vendor/etc/init/vendor.dolby.hardware.dms@2.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.dolby.hardware.dms@2.0-service.rc \
    vendor/sony/extra/extra/proprietary/vendor/etc/init/vendor.dolby.media.c2@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.dolby.media.c2@1.0-service.rc \
    vendor/sony/extra/extra/proprietary/vendor/etc/media_codecs_dolby_audio.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_dolby_audio.xml \
    vendor/sony/extra/extra/proprietary/vendor/etc/media_codecs_sony_c2_audio.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_sony_c2_audio.xml \
    vendor/sony/extra/extra/proprietary/vendor/etc/seccomp_policy/android.hardware.media.c2@1.2-default-seccomp_policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/android.hardware.media.c2@1.2-default-seccomp_policy \
    vendor/sony/extra/extra/proprietary/vendor/etc/windnoise_reduction.data:$(TARGET_COPY_OUT_VENDOR)/etc/windnoise_reduction.data \
    vendor/sony/extra/extra/proprietary/vendor/etc/windnoise_reduction_back.data:$(TARGET_COPY_OUT_VENDOR)/etc/windnoise_reduction_back.data \
    vendor/sony/extra/extra/proprietary/vendor/etc/windnoise_reduction_stat.data:$(TARGET_COPY_OUT_VENDOR)/etc/windnoise_reduction_stat.data \
    vendor/sony/extra/extra/proprietary/vendor/etc/windnoise_reduction_stat_back.data:$(TARGET_COPY_OUT_VENDOR)/etc/windnoise_reduction_stat_back.data \
    vendor/sony/extra/extra/proprietary/vendor/etc/zoom_noise_reduction/znr_Front_44k.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/zoom_noise_reduction/znr_Front_44k.tbl \
    vendor/sony/extra/extra/proprietary/vendor/etc/zoom_noise_reduction/znr_Front_48k.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/zoom_noise_reduction/znr_Front_48k.tbl \
    vendor/sony/extra/extra/proprietary/vendor/etc/zoom_noise_reduction/znr_Front_mono_44k.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/zoom_noise_reduction/znr_Front_mono_44k.tbl \
    vendor/sony/extra/extra/proprietary/vendor/etc/zoom_noise_reduction/znr_Front_mono_48k.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/zoom_noise_reduction/znr_Front_mono_48k.tbl \
    vendor/sony/extra/extra/proprietary/vendor/etc/zoom_noise_reduction/znr_Logical_44k.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/zoom_noise_reduction/znr_Logical_44k.tbl \
    vendor/sony/extra/extra/proprietary/vendor/etc/zoom_noise_reduction/znr_Logical_48k.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/zoom_noise_reduction/znr_Logical_48k.tbl \
    vendor/sony/extra/extra/proprietary/vendor/etc/zoom_noise_reduction/znr_Logical_mono_44k.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/zoom_noise_reduction/znr_Logical_mono_44k.tbl \
    vendor/sony/extra/extra/proprietary/vendor/etc/zoom_noise_reduction/znr_Logical_mono_48k.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/zoom_noise_reduction/znr_Logical_mono_48k.tbl \
    vendor/sony/extra/extra/proprietary/vendor/etc/zoom_noise_reduction/znr_P_Tele_44k.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/zoom_noise_reduction/znr_P_Tele_44k.tbl \
    vendor/sony/extra/extra/proprietary/vendor/etc/zoom_noise_reduction/znr_P_Tele_48k.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/zoom_noise_reduction/znr_P_Tele_48k.tbl \
    vendor/sony/extra/extra/proprietary/vendor/etc/zoom_noise_reduction/znr_P_Tele_mono_44k.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/zoom_noise_reduction/znr_P_Tele_mono_44k.tbl \
    vendor/sony/extra/extra/proprietary/vendor/etc/zoom_noise_reduction/znr_P_Tele_mono_48k.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/zoom_noise_reduction/znr_P_Tele_mono_48k.tbl \
    vendor/sony/extra/extra/proprietary/vendor/etc/zoom_noise_reduction/znr_P_UWide_44k.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/zoom_noise_reduction/znr_P_UWide_44k.tbl \
    vendor/sony/extra/extra/proprietary/vendor/etc/zoom_noise_reduction/znr_P_UWide_48k.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/zoom_noise_reduction/znr_P_UWide_48k.tbl \
    vendor/sony/extra/extra/proprietary/vendor/etc/zoom_noise_reduction/znr_P_UWide_mono_44k.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/zoom_noise_reduction/znr_P_UWide_mono_44k.tbl \
    vendor/sony/extra/extra/proprietary/vendor/etc/zoom_noise_reduction/znr_P_UWide_mono_48k.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/zoom_noise_reduction/znr_P_UWide_mono_48k.tbl \
    vendor/sony/extra/extra/proprietary/vendor/etc/zoom_noise_reduction/znr_P_Wide_44k.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/zoom_noise_reduction/znr_P_Wide_44k.tbl \
    vendor/sony/extra/extra/proprietary/vendor/etc/zoom_noise_reduction/znr_P_Wide_48k.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/zoom_noise_reduction/znr_P_Wide_48k.tbl \
    vendor/sony/extra/extra/proprietary/vendor/etc/zoom_noise_reduction/znr_P_Wide_mono_44k.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/zoom_noise_reduction/znr_P_Wide_mono_44k.tbl \
    vendor/sony/extra/extra/proprietary/vendor/etc/zoom_noise_reduction/znr_P_Wide_mono_48k.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/zoom_noise_reduction/znr_P_Wide_mono_48k.tbl \
    vendor/sony/extra/extra/proprietary/vendor/etc/zoom_noise_reduction/znr_default_44k.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/zoom_noise_reduction/znr_default_44k.tbl \
    vendor/sony/extra/extra/proprietary/vendor/etc/zoom_noise_reduction/znr_default_48k.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/zoom_noise_reduction/znr_default_48k.tbl \
    vendor/sony/extra/extra/proprietary/vendor/etc/zoom_noise_reduction/znr_parameter.xml:$(TARGET_COPY_OUT_VENDOR)/etc/zoom_noise_reduction/znr_parameter.xml \
    vendor/sony/extra/extra/proprietary/vendor/etc/zoom_noise_reduction/znr_parameter_back.xml:$(TARGET_COPY_OUT_VENDOR)/etc/zoom_noise_reduction/znr_parameter_back.xml

PRODUCT_PACKAGES += \
    libXtcApi \
    libaudiokeymgr \
    libaudiosnpewrapper \
    libaudiosnpewrapper_context \
    libcodec2_soft_ac4dec \
    libcodec2_soft_ddpdec \
    libcodec2_soft_dolby \
    libcodec2_soft_mha1dec \
    libcodec2_soft_mhm1dec \
    libcodec2_store_dolby \
    libdapparamstorage \
    libdeccfg \
    libdlbdsservice \
    libdlbpreg \
    libiVptApi \
    libiVptHkiDec \
    libiVptLibC \
    liboem_specific \
    librebuffering \
    libthreesixty_ra_codec2_store \
    libtsrspkenhance \
    libupmix-lib \
    libznr \
    libbundlewrapper1 \
    libbundlewrapper2 \
    libbundlewrapper3 \
    libbundlewrapper4 \
    libdlbvol \
    libdnnrwrapper \
    libswdap \
    libswgamedap \
    libswvqe \
    libtsrspatializer \
    libtsrupmix \
    libznrwrapper \
    vendor.dolby.hardware.dms@2.0-impl \
    vendor.dolby.hardware.dms@2.0 \
    libmepstarterjni \
    GamingAccessorySettings \
    GamingFanService \
    SomcDualshockManager \
    SomcMediaExtensionProviderStarter \
    ThermalFanService \
    ExtMonitorApp \
    SomcMediaExtensionProvider-Yodo \
    ThreeSixtyRASettings \
    DolbySound \
    SomcColorGamut \
    SoundEnhancement \
    ThreeSixtyRASystem \
    daxService \
    com.google.protobuf-2.3.0-dummy \
    com.sonymobile.home.resourceprovider \
    somc-ext-mmwdiapi \
    com.sony.threesixtyra.audiofx \
    com.sonymobile.gesdklibrary \
    vendor.dolby.hardware.dms.xml \
    vendor.dolby.media.c2@1.0-service.xml \
    vendor.threesixty_ra.codec2.xml \
    android.hardware.media.c2@1.0-threesixty-ra-service \
    vendor.dolby.hardware.dms@2.0-service \
    vendor.dolby.media.c2@1.0-service

PRODUCT_PACKAGES += \
    vendor.dolby.hardware.dms@2.0_vendor.dolby.hardware.dms@2.0_symlink64

include vendor/sony/extra/extra/overlays.mk
