LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_SHIPS_CUSTOM_DOLBY),true)

include $(CLEAR_VARS)
APKEDITOR := prebuilts/tools-parasite/common/bin/APKEditor
$(shell $(APKEDITOR) b -i $(LOCAL_PATH)/daxService -f -o $(LOCAL_PATH)/daxServiceCustom.apk)
LOCAL_MODULE := daxServiceCustom
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := daxServiceCustom.apk
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_CLASS := APPS
LOCAL_INSTALLED_MODULE_STEM := daxService.apk
LOCAL_SYSTEM_EXT_MODULE := true
LOCAL_PRIVILEGED_MODULE := true
LOCAL_MODULE_RELATIVE_PATH := daxService
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_NO_STANDARD_LIBRARIES := true
LOCAL_OVERRIDES_PACKAGES := daxService
LOCAL_MULTILIB := both
include $(BUILD_PREBUILT)

endif #TARGET_SHIPS_CUSTOM_DOLBY
