LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_SHIPS_CUSTOM_THREESIXRA_SYSTEM),true)

include $(CLEAR_VARS)
APKEDITOR := prebuilts/tools-parasite/common/bin/APKEditor
$(shell $(APKEDITOR) b -i $(LOCAL_PATH)/ThreeSixtyRASystem -f -o $(LOCAL_PATH)/ThreeSixtyRASystemCustom.apk)
LOCAL_MODULE := ThreeSixtyRASystemCustom
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := ThreeSixtyRASystemCustom.apk
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_CLASS := APPS
LOCAL_INSTALLED_MODULE_STEM := ThreeSixtyRASystem.apk
LOCAL_SYSTEM_EXT_MODULE := true
LOCAL_PRIVILEGED_MODULE := true
LOCAL_MODULE_RELATIVE_PATH := ThreeSixtyRASystem
LOCAL_ENFORCE_USES_LIBRARIES := false
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_NO_STANDARD_LIBRARIES := true
LOCAL_OVERRIDES_PACKAGES := ThreeSixtyRASystem
LOCAL_MULTILIB := both
include $(BUILD_PREBUILT)

endif #TARGET_SHIPS_CUSTOM_THREESIXRA_SYSTEM
