LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := ThreeSixtyRASystemCustom
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := ThreeSixtyRASystemCustom.apk
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_CLASS := APPS
LOCAL_INSTALLED_MODULE_STEM := ThreeSixtyRASystem.apk
LOCAL_SYSTEM_EXT_MODULE := true
LOCAL_PRIVILEGED_MODULE := true
LOCAL_MODULE_RELATIVE_PATH := ThreeSixtyRASystem
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_NO_STANDARD_LIBRARIES := true
LOCAL_OVERRIDES_PACKAGES := ThreeSixtyRASystem
LOCAL_MULTILIB := both
include $(BUILD_PREBUILT)
